### ISSUE TITLE
IFDHandler is undefined

### ISSUE THREAD

**Issue by dmitryTurov** [diegomura/jay-peg#4]
in exif marker [src/markers/exif.js](https://github.com/diegomura/jay-peg/blob/main/src/markers/exif.js#L270) IFDHandler is undefined. so printing an image with geolocation in [@react-pdf/renderer](https://github.com/diegomura/react-pdf/blob/master/packages/image/src/jpeg.js#L17) will throw an error.

@diegomura tell me if I can help. thanks in advance!

**Comment by diegomura** [comment]
Good catch! Will try to look at this soon. Will be traveling these days so might not be immediately, but shouldn't be a hard fix

**Comment by nikischin** [comment]
Oh thank you so much, I am running in the same issue unfortunately.
